name: dispatchtest
on: 
  workflow_dispatch:
    inputs:
      example:
        description: "content here"
        required: true
        default: "no content"

jobs:
  auth-and-dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.ORG_REPO_DISPATCH_APPID }}
          application_private_key: ${{ secrets.ORG_REPO_DISPATCH_KEY }}
      
      #- name: trigger external action
      #  id: call_action
      #  env:
      #    API_TOKEN_GITHUB: ${{ secrets.steps.get_workflow_token.outputs.token }}
      #  uses: catenax-ng/playground-target/Demo@v1
      
      - name: trigger-workflow
        id: call_action
        env:
          API_TOKEN_GITHUB: ${{ secrets.steps.get_workflow_token.outputs.token }}
        run: |
          curl \
            --request POST \
            --url https://api.github.com/repos/catenax-ng/playground-target/actions/workflows/example.yaml/dispatches \
            --header "authorization: Bearer ${{ API_TOKEN_GITHUB }}" \
            --header "Accept: application/vnd.github.v3+json" \
            --data '{"ref":"main"}' \
            --fail
